@urlDev=http://localhost:8000/apis/auth

### Register
POST  {{urlDev}}/register
Content-Type: application/json

{
    "email": "test111@gmail.com",
    "password": "12345678",
    "name": "test111"
}


### Login
POST  {{urlDev}}/login
Content-Type: application/json

{
    "email": "test1111@gmail.com",
    "password": "12345678"
}