@urlDev=http://localhost:8000/apis/irregular-verb

### Create comunication phrase
POST  {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA1MzIzNDQ0LCJleHAiOjE3MDU0MDk4NDR9.BSYn4XxQZfbKSPzmVQkS_BAGIDX-6WPnORVxbRMQN2c
Content-Type: application/json

{
    "v1": "test1",
    "v2": "test2",
    "v3": "test3",
    "mean": "testthoi"
}

### Get all comunication phrases
GET   {{urlDev}}/25

### Get comunication phrase
GET   {{urlDev}}/2

### Update comunication phrase
PATCH {{urlDev}}/2
Content-Type: application/json

{
    "content": "test3",
    "mean": "test1"
}

### Delete comunication phrase
DELETE  {{urlDev}}/32
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA1MzIzNDQ0LCJleHAiOjE3MDU0MDk4NDR9.BSYn4XxQZfbKSPzmVQkS_BAGIDX-6WPnORVxbRMQN2c
