@urlDev=http://localhost:8000/apis/users

### get me
GET {{urlDev}}/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6InRlc3QxMjM0NTY3QGdtYWlsLmNvbSIsImlhdCI6MTcwNTQ5ODMxMSwiZXhwIjoxNzA1NTg0NzExfQ.KgJz8s1A-fjU1PchkKWGF9G8JMQSbOjBH3YTb_MKaHI

### get all users
GET {{urlDev}}/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA1NDk0NTY1LCJleHAiOjE3MDU1ODA5NjV9.-Ltlj3J_SlUT6BDatoyPfcOmej-o6-rMIPfv1kMTu9I
### is ban user
PATCH  {{urlDev}}/toggle-ban/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA1NDkzMTE3LCJleHAiOjE3MDU1Nzk1MTd9.4IrqaJkkleiJzaYuVQQhZRjREEV-DsCVuKLRyL21kUo
Content-Type: application/json

{
    "feedback": "test"
}
### delete user
DELETE {{urlDev}}/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWF0IjoxNzA1NDk1NjcyLCJleHAiOjE3MDU1ODIwNzJ9.SBkQNGAnQfnMFuZSfN8OFHTE5IoSIiY8CMkZrUADv_E
### Update profile
PATCH  {{urlDev}}/update-profile/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6InRlc3QxMjM0NUBnbWFpbC5jb20iLCJpYXQiOjE3MDU0OTUyMjAsImV4cCI6MTcwNTU4MTYyMH0.VOt5unsKWkmDfUOO9yO-bp0Qu3gPn_0hcbWz1RJeRUE
Content-Type: application/json

{
    "name": "test12345",
    "avt": "1234"
}

### change password
PATCH  {{urlDev}}/update-password/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6InRlc3QxMjM0NTZAZ21haWwuY29tIiwiaWF0IjoxNzA1NDk1NDAwLCJleHAiOjE3MDU1ODE4MDB9.rdGdM8v7iB6vEO_UYGpK5mPIzD_LCjLT8dTAnbG6bzY
Content-Type: application/json

{
    "oldPassword": "12345678",
    "newPassword": "123456789"
}

### verify Code
POST {{urlDev}}/verify-code
Content-Type: application/json

{
   "email": "test123456@gmail.com"
}

### reset password
PATCH  {{urlDev}}/reset-password
Content-Type: application/json

{
   "email": "test123456@gmail.com",
   "code": 939843,
   "newPassword": "123456"
}